language: node_js
node_js:
  - "4"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g karma
  - npm install karma-phantomjs-launcher -save-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm test
