language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm rebuild
script:
- npm test
- npm run dist
deploy:
- provider: s3
  access_key_id: AKIAIZTGEZK2W4A55UBQ
  secret_access_key:
    secure: 
  bucket: zrecruit-bucket
  local_dir: dist
  skip_cleanup: true
  region: us-east-1
