language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm rebuild
script:
- npm test
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAIZTGEZK2W4A55UBQ
    secret_access_key:
      secure: IkVLbGPyruCI9mWinf12uwEvM/CQMZb9/kKWzMe4KBXZT2tsWErdWQ2E/+CPC6/+x5w8DjjUzCRCEBud+RuThSKATMNdl2vAhS++2GOdjg8ibfvOgCJhzI0RJiQoMZPZFxPNqjPXRJq/LPCPVmvBqjArxkKodTI4gzH8POr8n86qL4w9hoJeO4OGgWXbITsoLamjFDCPNS6Ig2NuIJSxEAh6NDi6oAgnwKNqxler42DVp9HBNIB8ZvynenDZk6MpIY70aUsgMwN8+Whhww4w0PNGi+JVbUbW0lq6619Xy+ylUaICQiWpbAE4RYbu2GW6xfJq/lI1BGSu1D/lbsrsEue7BtHCp6cuGPTDdyPflTrvD+Heg2vDEErnvkvxGUZSeHcF+v/4fCnX3Vwbnn4cS9+j563tH1mEh0ksqRA5Hj5Xer3n9hSnsog/y8LuTG8gFzWbL4B9/R57xmqu1V8vie2/wEpdLZWPwMd8RuUa1L14OqkcvUtdIY70bEGI+WNRl1oCK0CCXrF9KCDBWLERfqfF6JqAjd4Z6SEenSfkSypIH79C/G1XAjYK92thFXRboheI/d9KZ4fay9Gu2g2tTNFGC35yeoJwQgmx1/qZC2ymUiZVYE+UKAxyUakKVo286H63rcIGUwcX7khOurLksfBmIFkXyWmfwAUBXXdFzoE=
    bucket: zrecruit-bucket
    skip_cleanup: true
    region: us-east-1
