language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm rebuild
script:
- npm test
deploy:
  provider: s3
  access_key_id: AKIAJYTW6IWPXMGLR4JA
  secret_access_key:
    secure: Y8te0Natb9n9gegIf36OvTwy5XYQpR4aL65Gqx0ogXFNOIFjUl8c3HyVqWjL3cOnkoYGcofIAYCbI1Gqzyiu2LcfGIiFxPZW6fAQYJWk51TF/Q8JdsljOSGk0EU+46dlZoPCJ3lqu0bEiKNEbgZAooT/v7C9aO6Vfz2JMk6XuAKF+usDnuR3INdoqDB7JE2jUSBVzk4RzJhIpr7pxMQ91yn3JPWwYP6zhhdB6k9KLmFvECT7Zw+/9DhrK3Oh+DMqvOWg6v7hJxULL3qFZK9JUwSSf7AsQuL0gHwrwrDmMkK4eFBoYs2M5hKC9zIG/aJ6KQI1z2+H9dQl2k8njzzVcm+IEtoKypKO1gWKNwvpYcMKvopvDc+LKLTy0V0C2oOseAUrL1kJBNWxCA329fbeOkxZasL7NQ0/zGbyfFR3yjw/8WCBFpAtkCcQdT1nGeroL/NyWxTE5to0zpufE2wCiEw0MDRdPUcM1F/PKGyfcQ0YemDY2tbf0fiA+XQvsTo9jkRJDAwVexGUOG1jYyFjXfMNQ6b/4Dx8KwdgRQiwyfOYZKD0Ai43kqLD8mU+V8RBJNVNZhs6Mu0vXKdG7Y4Y+OknDyFC9KI5EG4D4yhPLX1dAx7GaHuqZ6rkknP4blDS916PsvuVQBOCeL54DqBjiUqITP0LHdY9/5IrPHvgCNg=
  bucket: zrecruit-bucket
  skip_cleanup: true
  region: us-east-1
