language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm rebuild
script:
- npm test
deploy:
- provider: s3
  access_key_id: AKIAIZTGEZK2W4A55UBQ
  secret_access_key:
    secure: WcU3l7WcOSIZ2UuCh3Oq6zFuXRBq3t2+OtjV9sGrsBNd4UuGfwCky9fEH7hx6bB7pCOcwT48Esp5ET0aHSRSygAVrLQsNB+p98WnNMo2x032rS4UwJ722ree2abMmcsqBAaon6mDGfgOT1VuNfX1Lk06G/GGE6rL6ouVtzhB5wRBoMCsJc/I3UMZ14D2ofwSy1laOrdFMwllvXExDU3aG6xoXxt3OIUVa72gjXNLlxW+K/lC5PoX3WRvkc+AqB+NQ7HhNCdHu6/hRMtc9OHKze7sda7350qND+xAU4QbbfflpBxy0pTayxIwnJXxKUGyDSfLHF/Z9ACsr5LLYjuekjXQcrr+0l+xzUqI1XC7nj9fSs+6DbsaAhIc4UirCmOkFh33HI0utiCO94AUYBGjsSmR2zdsdlaX3nN5uIt92jlVsEdFszp9a/pteeSReTUcE9KHJ5KM2tsVeun3spCAUGgFV/hL4xuCRqDL3Dazke6N8kVXFZJBREVWowyUhOAF1jIKO7vhP9WblSCQZesh9wdqNOM3Xaog6vMH1/g7BDYf0r//wohHXOk916bReNx1baW2wPQ7ao5RWUeO7naZs6PkoSnRoG32Lr0TyZK9voiYazP/B8aRv062D/NOZiPu6a9aXkPKECexeOXISW+gz2+XgvRbXSlqdUEjqnp0Z9Q=
  bucket: zrecruit-bucket
  skip_cleanup: true
  region: us-east-1
